import React from "react";
import styles from "./donate.module.css";

function Donate() {
  return (
    <div className={styles.donate}>
      <h1> DONATE HERE</h1>
      <p>
        {" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE DONATE
        DONATE DONATE DONATE DONATE DONATE DONATE DONATE{" "}
      </p>
    </div>
  );
}

export default Donate;
